language: php

php:
  - 5.3
  - 5.6
  - hhvm

install:
 - composer self-update
 - composer install

script:
 - vendor/bin/phpcs --extensions=php --standard=PSR1 --report=emacs src unit
 - vendor/bin/phpcs --extensions=php --standard=PSR2 --report=emacs src unit
 - vendor/bin/phpcs --extensions=php --standard=PEAR --report=emacs src unit
 - vendor/bin/phpunit unit

notifications:
  email:
    - h-yoshida@mediba.jp
